<?php
/**
 * Location Data for Indian Cities & States
 * Used by location-seo.php to generate unique E-E-A-T content per city
 * Each entry: [display_name, state, tier, industries[], population_desc]
 */

$location_data = [
    // --- MAJOR METROS (Tier 1) ---
    'delhi' => ['Delhi', 'Delhi NCR', 'metro', ['government', 'IT', 'retail', 'hospitality', 'real estate', 'education', 'healthcare'], 'the capital city with over 20 million residents'],
    'mumbai' => ['Mumbai', 'Maharashtra', 'metro', ['finance', 'entertainment', 'IT', 'manufacturing', 'pharmaceuticals', 'textiles'], 'India\'s financial capital with over 20 million residents'],
    'bengaluru' => ['Bengaluru', 'Karnataka', 'metro', ['IT', 'startups', 'biotechnology', 'aerospace', 'e-commerce', 'fintech'], 'India\'s Silicon Valley and tech hub'],
    'hyderabad' => ['Hyderabad', 'Telangana', 'metro', ['IT', 'pharmaceuticals', 'biotechnology', 'real estate', 'FMCG', 'e-commerce'], 'a major IT and pharma hub with a booming startup ecosystem'],
    'chennai' => ['Chennai', 'Tamil Nadu', 'metro', ['automobile', 'IT', 'healthcare', 'manufacturing', 'logistics', 'education'], 'the automobile capital of India'],
    'kolkata' => ['Kolkata', 'West Bengal', 'metro', ['jute', 'IT', 'steel', 'retail', 'education', 'FMCG'], 'the cultural capital of eastern India'],
    'pune' => ['Pune', 'Maharashtra', 'metro', ['IT', 'automobile', 'education', 'manufacturing', 'defence', 'startups'], 'India\'s leading education and IT hub'],
    'ahmedabad' => ['Ahmedabad', 'Gujarat', 'metro', ['textiles', 'pharmaceuticals', 'chemicals', 'IT', 'diamond cutting', 'real estate'], 'a major commercial hub and UNESCO World Heritage City'],

    // --- TIER 1 CITIES ---
    'jaipur' => ['Jaipur', 'Rajasthan', 'tier1', ['tourism', 'gems & jewellery', 'textiles', 'IT', 'handicrafts', 'real estate'], 'the Pink City and a top tourist destination'],
    'lucknow' => ['Lucknow', 'Uttar Pradesh', 'tier1', ['IT', 'food processing', 'handicrafts', 'real estate', 'education', 'healthcare'], 'the City of Nawabs and UP\'s capital'],
    'chandigarh' => ['Chandigarh', 'Chandigarh', 'tier1', ['IT', 'education', 'healthcare', 'real estate', 'tourism', 'retail'], 'one of India\'s best planned cities'],
    'indore' => ['Indore', 'Madhya Pradesh', 'tier1', ['IT', 'automobile', 'pharmaceuticals', 'food processing', 'textiles', 'education'], 'India\'s cleanest city and a growing commercial hub'],
    'bhopal' => ['Bhopal', 'Madhya Pradesh', 'tier1', ['IT', 'manufacturing', 'textiles', 'education', 'tourism', 'healthcare'], 'the City of Lakes and Madhya Pradesh\'s capital'],
    'nagpur' => ['Nagpur', 'Maharashtra', 'tier1', ['mining', 'agriculture', 'IT', 'real estate', 'textiles', 'logistics'], 'the Orange City at the geographic center of India'],
    'visakhapatnam' => ['Visakhapatnam', 'Andhra Pradesh', 'tier1', ['steel', 'shipping', 'IT', 'petrochemicals', 'fishing', 'tourism'], 'a major port city and industrial center'],
    'patna' => ['Patna', 'Bihar', 'tier1', ['agriculture', 'IT', 'education', 'healthcare', 'food processing', 'retail'], 'one of the oldest continuously inhabited cities in the world'],
    'vadodara' => ['Vadodara', 'Gujarat', 'tier1', ['petrochemicals', 'engineering', 'IT', 'education', 'culture', 'manufacturing'], 'a cultural and industrial city in Gujarat'],
    'gurgaon' => ['Gurgaon', 'Haryana', 'metro', ['IT', 'finance', 'consulting', 'e-commerce', 'startups', 'real estate'], 'India\'s millennium city and corporate hub near Delhi'],
    'noida' => ['Noida', 'Uttar Pradesh', 'tier1', ['IT', 'media', 'manufacturing', 'real estate', 'education', 'e-commerce'], 'a major IT and industrial hub in NCR'],
    'surat' => ['Surat', 'Gujarat', 'tier1', ['diamond cutting', 'textiles', 'IT', 'chemicals', 'logistics', 'real estate'], 'the diamond capital of the world'],
    'coimbatore' => ['Coimbatore', 'Tamil Nadu', 'tier1', ['textiles', 'engineering', 'IT', 'automotive parts', 'healthcare', 'education'], 'the Manchester of South India'],
    'kochi' => ['Kochi', 'Kerala', 'tier1', ['IT', 'shipping', 'tourism', 'spices', 'fishing', 'real estate'], 'the Queen of the Arabian Sea and Kerala\'s commercial capital'],
    'thiruvananthapuram' => ['Thiruvananthapuram', 'Kerala', 'tier1', ['IT', 'space research', 'tourism', 'education', 'healthcare', 'rubber'], 'Kerala\'s capital and a growing IT destination'],
    'vijayawada' => ['Vijayawada', 'Andhra Pradesh', 'tier1', ['agriculture', 'trade', 'IT', 'education', 'manufacturing', 'retail'], 'a major commercial center in Andhra Pradesh'],
    'madurai' => ['Madurai', 'Tamil Nadu', 'tier1', ['tourism', 'textiles', 'rubber', 'chemicals', 'education', 'healthcare'], 'the Temple City of India with over 2,500 years of history'],
    'amritsar' => ['Amritsar', 'Punjab', 'tier1', ['tourism', 'textiles', 'food processing', 'handicrafts', 'retail', 'hospitality'], 'the holy city and a major tourism destination'],
    'dehradun' => ['Dehradun', 'Uttarakhand', 'tier1', ['IT', 'education', 'tourism', 'agriculture', 'defence', 'healthcare'], 'the capital of Uttarakhand nestled in the foothills'],
    'mysuru' => ['Mysuru', 'Karnataka', 'tier1', ['IT', 'tourism', 'silk', 'sandalwood', 'education', 'manufacturing'], 'the City of Palaces and a heritage tourism hub'],

    // --- TIER 2 CITIES ---
    'agartala' => ['Agartala', 'Tripura', 'tier2', ['rubber', 'tea', 'bamboo', 'handloom', 'IT', 'agriculture'], 'the capital of Tripura and a northeastern gateway'],
    'ahmednagar' => ['Ahmednagar', 'Maharashtra', 'tier2', ['agriculture', 'sugar', 'automotive', 'education', 'textiles', 'dairy'], 'a historically significant city in Maharashtra'],
    'ajmer' => ['Ajmer', 'Rajasthan', 'tier2', ['tourism', 'handicrafts', 'textiles', 'marble', 'education', 'retail'], 'a pilgrimage city and tourist destination in Rajasthan'],
    'alappuzha' => ['Alappuzha', 'Kerala', 'tier2', ['tourism', 'coir', 'fishing', 'agriculture', 'houseboat industry', 'spices'], 'the Venice of the East known for its backwaters'],
    'alwar' => ['Alwar', 'Rajasthan', 'tier2', ['manufacturing', 'tourism', 'minerals', 'agriculture', 'dairy', 'retail'], 'a gateway to the Sariska Tiger Reserve'],
    'ambala' => ['Ambala', 'Haryana', 'tier2', ['scientific instruments', 'food processing', 'defence', 'agriculture', 'retail', 'logistics'], 'a major cantonment and scientific instruments hub'],
    'amravati' => ['Amravati', 'Maharashtra', 'tier2', ['agriculture', 'textiles', 'education', 'IT', 'cotton', 'manufacturing'], 'a major agricultural and education center in Vidarbha'],
    'anantapur' => ['Anantapur', 'Andhra Pradesh', 'tier2', ['mining', 'agriculture', 'education', 'textiles', 'diamond polishing', 'IT'], 'a growing city in Rayalaseema region'],
    'asansol' => ['Asansol', 'West Bengal', 'tier2', ['coal mining', 'steel', 'railways', 'manufacturing', 'education', 'retail'], 'a major industrial city in West Bengal\'s coal belt'],
    'aurangabad' => ['Aurangabad', 'Maharashtra', 'tier2', ['automobile', 'pharmaceuticals', 'tourism', 'IT', 'silk weaving', 'manufacturing'], 'the Tourism Capital of Maharashtra'],
    'ballari' => ['Ballari', 'Karnataka', 'tier2', ['mining', 'steel', 'agriculture', 'tourism', 'textiles', 'education'], 'a major mining and steel hub in Karnataka'],
    'bardhaman' => ['Bardhaman', 'West Bengal', 'tier2', ['agriculture', 'rice milling', 'education', 'manufacturing', 'coal', 'retail'], 'a significant cultural and agricultural center'],
    'belagavi' => ['Belagavi', 'Karnataka', 'tier2', ['manufacturing', 'textiles', 'sugar', 'agriculture', 'defence', 'IT'], 'a growing industrial city in north Karnataka'],
    'bhagalpur' => ['Bhagalpur', 'Bihar', 'tier2', ['silk weaving', 'agriculture', 'education', 'fishing', 'handicrafts', 'retail'], 'the Silk City of India'],
    'bharatpur' => ['Bharatpur', 'Rajasthan', 'tier2', ['tourism', 'agriculture', 'handicrafts', 'stone carving', 'mustard oil', 'retail'], 'home to the famous Keoladeo Bird Sanctuary'],
    'bhatinda' => ['Bhatinda', 'Punjab', 'tier2', ['agriculture', 'thermal power', 'oil refinery', 'education', 'cotton', 'retail'], 'an important energy and agricultural hub in Punjab'],
    'bhavnagar' => ['Bhavnagar', 'Gujarat', 'tier2', ['ship breaking', 'diamond polishing', 'agriculture', 'lock manufacturing', 'education', 'retail'], 'a major port city on the Gulf of Cambay'],
    'bhilai' => ['Bhilai', 'Chhattisgarh', 'tier2', ['steel', 'manufacturing', 'IT', 'education', 'coal', 'retail'], 'home to one of India\'s largest steel plants'],
    'bhilwara' => ['Bhilwara', 'Rajasthan', 'tier2', ['textiles', 'marble', 'zinc', 'agriculture', 'education', 'retail'], 'the Textile City of India'],
    'bhopal' => ['Bhopal', 'Madhya Pradesh', 'tier1', ['IT', 'manufacturing', 'textiles', 'education', 'tourism', 'healthcare'], 'the City of Lakes and state capital'],
    'bhubaneswar' => ['Bhubaneswar', 'Odisha', 'tier1', ['IT', 'tourism', 'education', 'steel', 'handicrafts', 'healthcare'], 'the Temple City and Odisha\'s smart city capital'],
    'bhuj' => ['Bhuj', 'Gujarat', 'tier2', ['handicrafts', 'tourism', 'textiles', 'agriculture', 'embroidery', 'retail'], 'the cultural heart of Kutch known for handicrafts'],
    'bikaner' => ['Bikaner', 'Rajasthan', 'tier2', ['tourism', 'wool', 'handicrafts', 'food processing', 'leather', 'retail'], 'a historic desert city famous for its snacks and camels'],
    'bilaspur' => ['Bilaspur', 'Chhattisgarh', 'tier2', ['power', 'coal', 'agriculture', 'education', 'railways', 'retail'], 'the judicial capital of Chhattisgarh'],
    'bokaro' => ['Bokaro', 'Jharkhand', 'tier2', ['steel', 'coal', 'mining', 'manufacturing', 'education', 'retail'], 'home to Bokaro Steel Plant, one of India\'s largest'],
    'brahmapur' => ['Brahmapur', 'Odisha', 'tier2', ['silk weaving', 'education', 'agriculture', 'fishing', 'handicrafts', 'retail'], 'the Silk City of Odisha'],
    'chandrapur' => ['Chandrapur', 'Maharashtra', 'tier2', ['coal mining', 'power', 'cement', 'agriculture', 'forestry', 'retail'], 'a major coal and power hub in Vidarbha'],
    'darbhanga' => ['Darbhanga', 'Bihar', 'tier2', ['agriculture', 'education', 'makhana', 'fisheries', 'handicrafts', 'retail'], 'the cultural capital of Mithila region'],
    'davanagere' => ['Davanagere', 'Karnataka', 'tier2', ['cotton', 'agriculture', 'education', 'benne dosa', 'handlooms', 'retail'], 'the Manchester of Karnataka'],
    'dhanbad' => ['Dhanbad', 'Jharkhand', 'tier2', ['coal mining', 'steel', 'mining education', 'manufacturing', 'railways', 'retail'], 'the Coal Capital of India'],
    'dharamshala' => ['Dharamshala', 'Himachal Pradesh', 'tier2', ['tourism', 'tea', 'handicrafts', 'IT', 'cricket', 'hospitality'], 'home to the Dalai Lama and a major hill station'],
    'dhule' => ['Dhule', 'Maharashtra', 'tier2', ['textiles', 'agriculture', 'jaggery', 'education', 'trading', 'retail'], 'a growing commercial center in north Maharashtra'],
    'dibrugarh' => ['Dibrugarh', 'Assam', 'tier2', ['tea', 'oil', 'coal', 'plywood', 'agriculture', 'education'], 'the Tea City of India'],
    'durgapur' => ['Durgapur', 'West Bengal', 'tier2', ['steel', 'coal', 'manufacturing', 'IT', 'cement', 'education'], 'the Ruhr of India and a major industrial city'],
    'erode' => ['Erode', 'Tamil Nadu', 'tier2', ['textiles', 'turmeric', 'agriculture', 'handlooms', 'education', 'retail'], 'the Turmeric City and textile hub'],
    'faridabad' => ['Faridabad', 'Haryana', 'tier1', ['manufacturing', 'engineering', 'automobile', 'textiles', 'IT', 'real estate'], 'a major industrial city in NCR'],
    'ghaziabad' => ['Ghaziabad', 'Uttar Pradesh', 'tier1', ['manufacturing', 'electronics', 'steel', 'IT', 'real estate', 'retail'], 'the Gateway of UP and a major NCR industrial hub'],
    'gorakhpur' => ['Gorakhpur', 'Uttar Pradesh', 'tier2', ['railways', 'terracotta', 'agriculture', 'education', 'healthcare', 'retail'], 'a major railway junction and cultural center'],
    'gulbarga' => ['Gulbarga', 'Karnataka', 'tier2', ['agriculture', 'cement', 'education', 'dal milling', 'textiles', 'retail'], 'an education and agricultural hub in north Karnataka'],
    'guntur' => ['Guntur', 'Andhra Pradesh', 'tier2', ['agriculture', 'chilli', 'tobacco', 'cotton', 'education', 'retail'], 'the Chilli Capital of India'],
    'guwahati' => ['Guwahati', 'Assam', 'tier1', ['IT', 'oil', 'tea', 'tourism', 'education', 'retail'], 'the Gateway to Northeast India'],
    'gwalior' => ['Gwalior', 'Madhya Pradesh', 'tier2', ['tourism', 'manufacturing', 'education', 'handicrafts', 'IT', 'retail'], 'a historic city known for its magnificent fort'],
    'hubli' => ['Hubli', 'Karnataka', 'tier2', ['cotton', 'IT', 'manufacturing', 'education', 'agriculture', 'retail'], 'a growing commercial hub in north Karnataka'],
    'jabalpur' => ['Jabalpur', 'Madhya Pradesh', 'tier2', ['ordnance', 'IT', 'tourism', 'education', 'manufacturing', 'retail'], 'the marble city and judicial capital of MP'],
    'jalandhar' => ['Jalandhar', 'Punjab', 'tier2', ['sports goods', 'rubber', 'hand tools', 'leather', 'education', 'retail'], 'the Sports Capital of India'],
    'jammu' => ['Jammu', 'Jammu & Kashmir', 'tier2', ['tourism', 'agriculture', 'handicrafts', 'walnut', 'education', 'retail'], 'the City of Temples and winter capital of J&K'],
    'jamnagar' => ['Jamnagar', 'Gujarat', 'tier2', ['oil refinery', 'brass', 'bandhani', 'agriculture', 'gems', 'retail'], 'home to the world\'s largest oil refinery'],
    'jamshedpur' => ['Jamshedpur', 'Jharkhand', 'tier2', ['steel', 'automobile', 'mining', 'IT', 'cement', 'manufacturing'], 'the Steel City of India, home to Tata Steel'],
    'jhansi' => ['Jhansi', 'Uttar Pradesh', 'tier2', ['tourism', 'agriculture', 'defence', 'education', 'handicrafts', 'retail'], 'the Gateway to Bundelkhand with rich heritage'],
    'jodhpur' => ['Jodhpur', 'Rajasthan', 'tier2', ['tourism', 'handicrafts', 'textiles', 'sandstone', 'agriculture', 'retail'], 'the Blue City and Sun City of India'],
    'kakinada' => ['Kakinada', 'Andhra Pradesh', 'tier2', ['oil & gas', 'fishing', 'agriculture', 'port', 'education', 'retail'], 'a major port city and oil basin hub'],
    'kannur' => ['Kannur', 'Kerala', 'tier2', ['handloom', 'coir', 'fishing', 'tourism', 'cashew', 'education'], 'the Land of Looms and Lores'],
    'kanpur' => ['Kanpur', 'Uttar Pradesh', 'tier1', ['leather', 'textiles', 'IT', 'chemical', 'education', 'manufacturing'], 'the Leather City and Manchester of India'],
    'karimnagar' => ['Karimnagar', 'Telangana', 'tier2', ['granite', 'agriculture', 'silver filigree', 'education', 'handlooms', 'retail'], 'known for silver filigree work and granite'],
    'khammam' => ['Khammam', 'Telangana', 'tier2', ['agriculture', 'mining', 'forestry', 'education', 'rice milling', 'retail'], 'an agricultural heartland in Telangana'],
    'kolhapur' => ['Kolhapur', 'Maharashtra', 'tier2', ['sugar', 'foundry', 'dairy', 'jaggery', 'footwear', 'education'], 'famous for Kolhapuri chappals and jaggery'],
    'kollam' => ['Kollam', 'Kerala', 'tier2', ['cashew', 'coir', 'fishing', 'tourism', 'backwaters', 'education'], 'the Cashew Capital of the World'],
    'kota' => ['Kota', 'Rajasthan', 'tier2', ['education', 'coaching', 'power', 'chemicals', 'Kota stone', 'retail'], 'India\'s coaching capital for IIT/Medical entrance'],
    'kozhikode' => ['Kozhikode', 'Kerala', 'tier2', ['IT', 'timber', 'spices', 'tourism', 'education', 'healthcare'], 'the City of Spices and Malabar\'s commercial capital'],
    'kurnool' => ['Kurnool', 'Andhra Pradesh', 'tier2', ['agriculture', 'textiles', 'cement', 'education', 'mining', 'retail'], 'the former capital of Andhra Pradesh'],
    'ludhiana' => ['Ludhiana', 'Punjab', 'tier2', ['hosiery', 'bicycle', 'machine tools', 'auto parts', 'textiles', 'retail'], 'the Manchester of India for hosiery and textiles'],
    'mangaluru' => ['Mangaluru', 'Karnataka', 'tier2', ['port', 'tiles', 'coffee', 'cashew', 'IT', 'education'], 'a major port city and the ice cream capital of Karnataka'],
    'meerut' => ['Meerut', 'Uttar Pradesh', 'tier2', ['sports goods', 'scissors', 'education', 'agriculture', 'manufacturing', 'retail'], 'a sports goods manufacturing hub'],
    'moradabad' => ['Moradabad', 'Uttar Pradesh', 'tier2', ['brass', 'handicrafts', 'export', 'agriculture', 'education', 'retail'], 'the Brass City of India'],
    'muzaffarpur' => ['Muzaffarpur', 'Bihar', 'tier2', ['litchi', 'agriculture', 'education', 'dairy', 'food processing', 'retail'], 'the Litchi Kingdom of India'],
    'nanded' => ['Nanded', 'Maharashtra', 'tier2', ['agriculture', 'sugar', 'handlooms', 'pilgrimage', 'education', 'retail'], 'a major Sikh pilgrimage center'],
    'nashik' => ['Nashik', 'Maharashtra', 'tier2', ['wine', 'grapes', 'defence', 'IT', 'manufacturing', 'tourism'], 'the Wine Capital of India'],
    'nellore' => ['Nellore', 'Andhra Pradesh', 'tier2', ['aquaculture', 'agriculture', 'mining', 'education', 'retail', 'shrimp'], 'a major aquaculture and shrimp hub'],
    'nizamabad' => ['Nizamabad', 'Telangana', 'tier2', ['agriculture', 'turmeric', 'sugar', 'handlooms', 'education', 'retail'], 'known for turmeric production and agriculture'],
    'raipur' => ['Raipur', 'Chhattisgarh', 'tier1', ['steel', 'power', 'rice', 'IT', 'education', 'retail'], 'the capital of Chhattisgarh and a steel hub'],
    'rajkot' => ['Rajkot', 'Gujarat', 'tier2', ['engineering', 'casting', 'auto parts', 'watch', 'education', 'retail'], 'a major auto parts and engineering hub'],
    'ranchi' => ['Ranchi', 'Jharkhand', 'tier1', ['mining', 'steel', 'IT', 'education', 'healthcare', 'retail'], 'the capital of Jharkhand and City of Waterfalls'],
    'rohtak' => ['Rohtak', 'Haryana', 'tier2', ['education', 'agriculture', 'stainless steel', 'healthcare', 'IT', 'retail'], 'a major education and healthcare hub'],
    'salem' => ['Salem', 'Tamil Nadu', 'tier2', ['steel', 'textiles', 'mangoes', 'agriculture', 'education', 'retail'], 'the Steel City of Tamil Nadu'],
    'sangli' => ['Sangli', 'Maharashtra', 'tier2', ['turmeric', 'grapes', 'sugar', 'agriculture', 'handlooms', 'education'], 'the Turmeric City of Maharashtra'],
    'shimla' => ['Shimla', 'Himachal Pradesh', 'tier2', ['tourism', 'apple', 'handicrafts', 'education', 'IT', 'hospitality'], 'the Queen of Hills and HP\'s capital'],
    'siliguri' => ['Siliguri', 'West Bengal', 'tier2', ['tea', 'timber', 'tourism', 'trade', 'jute', 'education'], 'the Gateway to Northeast India and a major trade hub'],
    'solapur' => ['Solapur', 'Maharashtra', 'tier2', ['textiles', 'beedi', 'sugar', 'towels', 'chaddars', 'education'], 'the Textile City famous for chaddar and towels'],
    'srinagar' => ['Srinagar', 'Jammu & Kashmir', 'tier2', ['tourism', 'handicrafts', 'shawls', 'dry fruits', 'saffron', 'houseboat'], 'the summer capital of J&K and jewel of Kashmir'],
    'thanjavur' => ['Thanjavur', 'Tamil Nadu', 'tier2', ['agriculture', 'art', 'temples', 'painting', 'music', 'education'], 'the Rice Bowl of Tamil Nadu and art capital'],
    'thoothukudi' => ['Thoothukudi', 'Tamil Nadu', 'tier2', ['port', 'salt', 'pearl', 'fishing', 'chemicals', 'education'], 'the Pearl City of India'],
    'thrissur' => ['Thrissur', 'Kerala', 'tier2', ['gold jewellery', 'banking', 'tourism', 'textiles', 'education', 'retail'], 'the Cultural Capital of Kerala and gold hub'],
    'tiruchirappalli' => ['Tiruchirappalli', 'Tamil Nadu', 'tier2', ['engineering', 'gems', 'temples', 'education', 'manufacturing', 'retail'], 'a major temple city and education hub'],
    'tirunelveli' => ['Tirunelveli', 'Tamil Nadu', 'tier2', ['agriculture', 'matchbox', 'wind energy', 'education', 'handicrafts', 'retail'], 'known for halwa and wind energy production'],
    'tumakuru' => ['Tumakuru', 'Karnataka', 'tier2', ['coconut', 'silk', 'education', 'agriculture', 'IT', 'manufacturing'], 'the Coconut City and a growing industrial hub'],
    'udaipur' => ['Udaipur', 'Rajasthan', 'tier2', ['tourism', 'zinc', 'marble', 'handicrafts', 'hospitality', 'education'], 'the City of Lakes and Venice of the East'],
    'udupi' => ['Udupi', 'Karnataka', 'tier2', ['tourism', 'banking', 'education', 'fishing', 'temples', 'hospitality'], 'the temple town known for Udupi cuisine'],
    'ujjain' => ['Ujjain', 'Madhya Pradesh', 'tier2', ['tourism', 'textiles', 'agriculture', 'education', 'pilgrimage', 'retail'], 'one of the seven sacred cities of Hinduism'],
    'vellore' => ['Vellore', 'Tamil Nadu', 'tier2', ['leather', 'healthcare', 'automobile', 'education', 'IT', 'retail'], 'home to CMC Vellore and a leather industry hub'],
    'warangal' => ['Warangal', 'Telangana', 'tier2', ['IT', 'education', 'textiles', 'agriculture', 'tourism', 'retail'], 'a heritage city with a growing IT sector'],
    'yamunanagar' => ['Yamunanagar', 'Haryana', 'tier2', ['paper', 'plywood', 'sugar', 'agriculture', 'timber', 'retail'], 'a major paper and plywood manufacturing center'],

    // --- STATES (used for state-level pages) ---
    'andhra-pradesh' => ['Andhra Pradesh', 'Andhra Pradesh', 'state', ['IT', 'agriculture', 'aquaculture', 'pharmaceuticals', 'tourism', 'mining'], 'a rapidly developing state with a strong IT sector'],
    'arunachal-pradesh' => ['Arunachal Pradesh', 'Arunachal Pradesh', 'state', ['tourism', 'hydropower', 'horticulture', 'handlooms', 'forestry', 'agriculture'], 'the Land of the Rising Sun in northeast India'],
    'assam' => ['Assam', 'Assam', 'state', ['tea', 'oil & gas', 'silk', 'tourism', 'agriculture', 'bamboo'], 'the tea capital of India'],
    'bihar' => ['Bihar', 'Bihar', 'state', ['agriculture', 'education', 'tourism', 'food processing', 'IT', 'handicrafts'], 'a state with rich cultural heritage and growing economy'],
    'chhattisgarh' => ['Chhattisgarh', 'Chhattisgarh', 'state', ['steel', 'mining', 'power', 'rice', 'forestry', 'IT'], 'the rice bowl of India with vast mineral resources'],
    'goa' => ['Goa', 'Goa', 'state', ['tourism', 'mining', 'pharmaceuticals', 'IT', 'fishing', 'hospitality'], 'India\'s premier beach destination and tourism hub'],
    'gujarat' => ['Gujarat', 'Gujarat', 'state', ['petrochemicals', 'diamond', 'textiles', 'pharmaceuticals', 'dairy', 'IT'], 'the growth engine of India'],
    'haryana' => ['Haryana', 'Haryana', 'state', ['IT', 'automobile', 'agriculture', 'manufacturing', 'real estate', 'education'], 'a major industrial and IT hub near Delhi'],
    'himachal-pradesh' => ['Himachal Pradesh', 'Himachal Pradesh', 'state', ['tourism', 'hydropower', 'apple', 'IT', 'handicrafts', 'pharmaceuticals'], 'the fruit bowl of India and tourism paradise'],
    'jharkhand' => ['Jharkhand', 'Jharkhand', 'state', ['mining', 'steel', 'coal', 'IT', 'forestry', 'manufacturing'], 'India\'s mineral treasure with vast natural resources'],
    'karnataka' => ['Karnataka', 'Karnataka', 'state', ['IT', 'biotechnology', 'aerospace', 'silk', 'coffee', 'manufacturing'], 'the Silicon State of India'],
    'kerala' => ['Kerala', 'Kerala', 'state', ['tourism', 'IT', 'spices', 'rubber', 'coir', 'healthcare'], 'God\'s Own Country with highest literacy rate'],
    'madhya-pradesh' => ['Madhya Pradesh', 'Madhya Pradesh', 'state', ['agriculture', 'mining', 'IT', 'tourism', 'textiles', 'manufacturing'], 'the Heart of India with diverse industries'],
    'maharashtra' => ['Maharashtra', 'Maharashtra', 'state', ['finance', 'IT', 'entertainment', 'manufacturing', 'agriculture', 'pharmaceuticals'], 'India\'s economic powerhouse and most industrialized state'],
    'manipur' => ['Manipur', 'Manipur', 'state', ['handlooms', 'handicrafts', 'agriculture', 'tourism', 'horticulture', 'sports'], 'the Jewel of India known for handlooms'],
    'meghalaya' => ['Meghalaya', 'Meghalaya', 'state', ['mining', 'tourism', 'agriculture', 'coal', 'limestone', 'education'], 'the Abode of Clouds with rich biodiversity'],
    'mizoram' => ['Mizoram', 'Mizoram', 'state', ['bamboo', 'agriculture', 'handlooms', 'tourism', 'horticulture', 'education'], 'the Land of Blue Mountains'],
    'nagaland' => ['Nagaland', 'Nagaland', 'state', ['handlooms', 'handicrafts', 'tourism', 'agriculture', 'horticulture', 'education'], 'the Land of Festivals in northeast India'],
    'odisha' => ['Odisha', 'Odisha', 'state', ['mining', 'steel', 'IT', 'handicrafts', 'tourism', 'agriculture'], 'the Soul of India with rich mineral wealth'],
    'punjab' => ['Punjab', 'Punjab', 'state', ['agriculture', 'sports goods', 'textiles', 'IT', 'food processing', 'manufacturing'], 'the breadbasket of India'],
    'rajasthan' => ['Rajasthan', 'Rajasthan', 'state', ['tourism', 'textiles', 'mining', 'handicrafts', 'gems', 'agriculture'], 'the Land of Kings and India\'s largest state'],
    'sikkim' => ['Sikkim', 'Sikkim', 'state', ['tourism', 'organic farming', 'hydropower', 'cardamom', 'education', 'handicrafts'], 'India\'s first fully organic state'],
    'tamil-nadu' => ['Tamil Nadu', 'Tamil Nadu', 'state', ['automobile', 'IT', 'textiles', 'manufacturing', 'healthcare', 'education'], 'the Detroit of Asia and India\'s industrial powerhouse'],
    'telangana' => ['Telangana', 'Telangana', 'state', ['IT', 'pharmaceuticals', 'biotechnology', 'agriculture', 'mining', 'real estate'], 'India\'s newest state and a major IT hub'],
    'tripura' => ['Tripura', 'Tripura', 'state', ['rubber', 'tea', 'bamboo', 'handlooms', 'agriculture', 'IT'], 'a northeastern state with growing IT potential'],
    'uttar-pradesh' => ['Uttar Pradesh', 'Uttar Pradesh', 'state', ['agriculture', 'IT', 'tourism', 'handicrafts', 'leather', 'food processing'], 'India\'s most populous state with vast market potential'],
    'uttarakhand' => ['Uttarakhand', 'Uttarakhand', 'state', ['tourism', 'IT', 'agriculture', 'hydropower', 'pharmaceuticals', 'education'], 'the Land of Gods with booming IT sector'],
    'west-bengal' => ['West Bengal', 'West Bengal', 'state', ['IT', 'jute', 'tea', 'steel', 'manufacturing', 'education'], 'the cultural and intellectual capital of India'],
];

// Service type mapping
$service_types = [
    'google-ads-services-agency' => ['Google Ads Services', 'Google Ads management', 'paid search advertising', 'PPC campaigns on Google'],
    'ppc-services-agency' => ['PPC Services', 'pay-per-click advertising', 'paid advertising campaigns', 'performance marketing'],
    'social-media-marketing-agency' => ['Social Media Marketing', 'social media management', 'Facebook, Instagram & LinkedIn marketing', 'social brand building'],
    'local-seo-agency' => ['Local SEO', 'local search optimization', 'Google Business Profile optimization', 'local map rankings'],
    'ecommerce-seo-agency' => ['E-commerce SEO', 'online store optimization', 'product page SEO', 'e-commerce search rankings'],
    'content-marketing-agency' => ['Content Marketing', 'content strategy & creation', 'blog writing & SEO content', 'content-driven growth'],
    'facebook-instagram-ads-agency' => ['Facebook & Instagram Ads', 'Meta advertising', 'social media paid campaigns', 'Facebook & Instagram lead generation'],
    'youtube-marketing-agency' => ['YouTube Marketing', 'video marketing & YouTube ads', 'YouTube channel growth', 'video advertising'],
    'ui-ux-design-agency' => ['UI/UX Design', 'user interface & experience design', 'app & web design', 'conversion-focused design'],
    'landing-page-design-agency' => ['Landing Page Design', 'high-converting landing pages', 'campaign landing pages', 'lead generation pages'],
    'creative-services-agency' => ['Creative Services', 'graphic design & branding', 'visual identity design', 'marketing creatives'],
    'video-editing-agency' => ['Video Editing', 'professional video production', 'ad video creation', 'social media video editing'],
    'best-digital-marketing-agency' => ['Digital Marketing', 'full-service digital marketing', '360-degree digital growth', 'online marketing solutions'],
    'seo-company' => ['SEO Services', 'search engine optimization', 'organic search rankings', 'website SEO audit & optimization'],
    'wordpress-website-development-agency' => ['WordPress Development', 'WordPress website design', 'custom WordPress solutions', 'WordPress CMS development'],
    'ecommerce-website-development-agency' => ['E-commerce Website Development', 'online store development', 'Shopify & WooCommerce development', 'e-commerce web solutions'],
];
?>
